### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by bagusflyer** [florinn/angular-typescript-gulp-seed#1]
Got an error message:

> [00:05:08] Starting 'scripts:app'...
> [gulp-typescript] 2345 Argument of type '{}' is not assignable to parameter of type 'string'.
> file: /Users/zhouhao/Projects/angular/angular-typescript-gulp-seed/app/todo/todo.controller.ts:
> [38]         ];
> [00:05:10] TypeScript: 1 semantic error

Although I can still run the app. Anything wrong (I didn't change anything) ? Thanks.

**Comment by grwgreg** [comment]
I just came across this same issue. Replacing line 38 with either of these fixes the problem,

$scope.$watch(() => $location.path(), path => this.onPath(path));

or

 $scope.$watch('location.path()', function(path) {
    this.onPath(path) 
}.bind(this));

I guess typescript has trouble handling $watch if passed a string to evaulate?

**Comment by florinn** [comment]
Another way to fix the error is to add the type argument as such:

``` typescript
$scope.$watch<string>('location.path()', path => this.onPath(path));
```

Thanks for pointing it out.
